"""add phone_number to user

Revision ID: 28798ee50a49
Revises: 19c087f720a0
Create Date: 2026-01-15 23:57:05.083396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28798ee50a49'
down_revision = '19c087f720a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captain_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sport', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('skill_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('open_for_requests', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['captain_id'], ['id'])
        batch_op.drop_column('skill_required')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_required', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('open_for_requests')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('area')
        batch_op.drop_column('city')
        batch_op.drop_column('skill_level')
        batch_op.drop_column('sport')
        batch_op.drop_column('captain_id')

    # ### end Alembic commands ###
