"""Add booking fields fixed

Revision ID: 9646f559c7f0
Revises: cd8b51e4ebf3
Create Date: 2026-01-06 22:49:37.622444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9646f559c7f0'
down_revision = 'cd8b51e4ebf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turf_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('booking_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guest_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guest_phone', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'turfs', ['turf_id'], ['id'])

    with op.batch_alter_table('turfs', schema=None) as batch_op:
        batch_op.alter_column('amenities',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('price_per_hour')
        batch_op.drop_column('surface_type')
        batch_op.drop_column('sports')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sports', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('surface_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_per_hour', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('amenities',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('guest_phone')
        batch_op.drop_column('guest_name')
        batch_op.drop_column('booking_source')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('turf_id')

    # ### end Alembic commands ###
